# Generated by Django 2.2.28 on 2022-06-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionObject',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_exhibition_exhibitionobject', serialize=False, to='cms.CMSPlugin')),
                ('author', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('name_fr', models.CharField(max_length=255)),
                ('description_fr', models.TextField()),
                ('name_de', models.CharField(max_length=255)),
                ('description_de', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
