# Generated by Django 3.2.14 on 2022-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0004_auto_20220823_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitionobject',
            old_name='date_object',
            new_name='date_object_de',
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='date_object_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='date_object_fr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
