# Generated by Django 5.0.2 on 2024-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0006_alter_exhibitionobject_cmsplugin_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
