# Generated by Django 5.0.2 on 2024-10-02 12:04

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0007_exhibitionobject_image'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionobject',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exhibition_object_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
