# Generated by Django 2.2.28 on 2022-06-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('mysite', '0002_exhibitionobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExhibitionObject',
        ),
    ]
