# Generated by Django 3.2.14 on 2022-07-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('mysite', '0003_delete_exhibitionobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
