# Generated by Django 3.2.14 on 2022-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='exhibitionobject',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='comment_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='comment_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='date_author',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='date_object',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='info_object',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
