# Generated by Django 3.2.14 on 2022-07-27 07:41

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0002_auto_20220727_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionobject',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='comment_de',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='comment_en',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='comment_fr',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='date_author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='date_object',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionobject',
            name='info_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
