# Generated by Django 3.2.14 on 2022-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_exhibition', '0003_auto_20220727_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitionobject',
            old_name='info_object',
            new_name='info_object_de',
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='info_object_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitionobject',
            name='info_object_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
