# Generated by Django 5.0.2 on 2024-12-24 10:31

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_jigsaw_puzzle.imageset')),
            ],
        ),
        migrations.CreateModel(
            name='JigsawPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.difficultylevel')),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.imageset')),
            ],
        ),
    ]
