# Generated by Django 5.0.2 on 2024-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultylevel',
            name='name',
            field=models.CharField(default='foo', max_length=128),
            preserve_default=False,
        ),
    ]
