# Generated by Django 5.0.2 on 2025-01-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_jigsaw_puzzle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGame',
            fields=[
                ('imagegame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_jigsaw_puzzle.imagegame')),
            ],
            bases=('django_jigsaw_puzzle.imagegame',),
        ),
        migrations.RemoveField(
            model_name='game',
            name='grid_difficulty_level',
        ),
        migrations.RemoveField(
            model_name='griddifficultylevel',
            name='jigsaw_puzzle',
        ),
        migrations.AddField(
            model_name='griddifficultylevel',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.game'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MemoryGamePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('memory_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.memorygame')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
