# Generated by Django 5.0.2 on 2025-01-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0002_memorygame_remove_game_grid_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jigsawpuzzlepluginmodel',
            old_name='jigsaw_puzzle',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='memorygamepluginmodel',
            old_name='memory_game',
            new_name='game',
        ),
    ]
