# Generated by Django 5.0.2 on 2024-12-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0002_difficultylevel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JigsawPuzzleDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.difficultylevel')),
                ('jigsaw_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.jigsawpuzzle')),
            ],
        ),
    ]
