# Generated by Django 5.0.2 on 2024-12-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0003_jigsawpuzzledifficultylevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigsawpuzzle',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='jigsawpuzzle',
            name='jigsaw_puzzle_difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.jigsawpuzzledifficultylevel'),
        ),
    ]
