# Generated by Django 5.0.2 on 2025-02-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0004_memorygame_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorygame',
            old_name='image',
            new_name='card_back_image',
        ),
    ]
