# Generated by Django 5.0.2 on 2024-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0004_remove_jigsawpuzzle_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigsawpuzzle',
            name='color',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AddField(
            model_name='jigsawpuzzle',
            name='copyright_notice',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jigsawpuzzle',
            name='randomize_images',
            field=models.BooleanField(default=True),
        ),
    ]
