# Generated by Django 5.0.2 on 2024-12-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_jigsaw_puzzle', '0005_jigsawpuzzle_color_jigsawpuzzle_copyright_notice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JigsawPuzzlePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('jigsaw_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.jigsawpuzzle')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
