# Generated by Django 5.0.2 on 2025-02-02 18:51

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0005_rename_image_memorygame_card_back_image'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='card_hidden_image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_hidden_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygame',
            name='card_back_image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_back_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
