# Generated by Django 5.0.2 on 2025-02-02 20:30

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_jigsaw_puzzle', '0006_memorygame_card_hidden_image_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_jigsaw_puzzle.game')),
            ],
            bases=('django_jigsaw_puzzle.game',),
        ),
        migrations.AlterField(
            model_name='memorygame',
            name='card_back_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_back_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygame',
            name='card_hidden_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_hidden_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.CreateModel(
            name='PaintPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.paintgame')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
