# Generated by Django 5.0.2 on 2025-02-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_jigsaw_puzzle', '0007_paintgame_alter_memorygame_card_back_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaintPluginModel',
            new_name='PaintGamePluginModel',
        ),
    ]
