# Generated by Django 5.0.2 on 2025-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0008_rename_paintpluginmodel_paintgamepluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='card_aspect_ratio',
            field=models.CharField(default='1 / 1', max_length=64),
        ),
    ]
