# Generated by Django 5.0.2 on 2025-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0009_memorygame_card_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='card_front_background_color',
            field=models.CharField(default='#222', max_length=7),
        ),
    ]
