# Generated by Django 5.2 on 2025-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0011_memorygame_card_width_alter_game_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintgame',
            name='allow_take_home',
            field=models.BooleanField(default=True, verbose_name='Allow the user to take home their painting by scanning a QR-Code. This also saves the painting in the CMS.'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='color_count_brightness',
            field=models.IntegerField(default=3, verbose_name='The amount of different brightnesses for each color.'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='color_count_gray',
            field=models.IntegerField(default=5, verbose_name='The amount of gray colors including black and white'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='color_count_hue',
            field=models.IntegerField(default=7, verbose_name='The amount of different colors like blue, green or yellow.'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='color_count_skin',
            field=models.IntegerField(default=5, verbose_name='The amount of skin colors.'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='idle_first_seconds',
            field=models.IntegerField(default=300, verbose_name='The amount of seconds until an idle warning is shown. If the users ignores it, the game will eventually be reset.'),
        ),
        migrations.AddField(
            model_name='paintgame',
            name='idle_second_seconds',
            field=models.IntegerField(default=330, verbose_name='The amount of seconds until the idle warning disappears automatically and the game is reset.'),
        ),
    ]
