# Generated by Django 5.2 on 2025-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0012_paintgame_allow_take_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintgame',
            name='color_count_hue',
            field=models.IntegerField(default=11, verbose_name='The amount of different colors like blue, green or yellow.'),
        ),
    ]
