# Generated by Django 5.2 on 2025-08-02 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0013_alter_paintgame_color_count_hue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_session_key', models.CharField(max_length=40)),
                ('player_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='QuizGame',
            fields=[
                ('basegame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_jigsaw_puzzle.basegame')),
            ],
            bases=('django_jigsaw_puzzle.basegame',),
        ),
        migrations.CreateModel(
            name='GameSessionPartialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_boolean', models.BooleanField(blank=True, null=True)),
                ('result_number', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_jigsaw_puzzle.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2048)),
                ('answer_1', models.CharField(max_length=1024)),
                ('answer_2', models.CharField(max_length=1024)),
                ('answer_3', models.CharField(max_length=1024)),
                ('answer_4', models.CharField(max_length=1024)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.quizgame')),
            ],
        ),
    ]
