# Generated by Django 5.2 on 2025-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0014_basegame_gamegroup_gamesession_quizgame_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
