# Generated by Django 5.2 on 2025-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0015_quiz_game_and_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='copyright_notice',
        ),
        migrations.AddField(
            model_name='imagegame',
            name='copyright_notice',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
