# Generated by Django 5.2 on 2025-09-18 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0015_alter_quizquestion_options_quizquestion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='django_session_key',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gamesessionpartialresult',
            name='session',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gamesessionpartialresult',
            name='game_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partial_results', to='django_jigsaw_puzzle.gamesession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesessionpartialresult',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partial_results', to='django_jigsaw_puzzle.quizquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesessionpartialresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
