# Generated by Django 5.2 on 2025-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0016_remove_game_copyright_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
