# Generated by Django 5.2 on 2025-09-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0016_remove_gamesession_django_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
