# Generated by Django 5.2 on 2025-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0017_quizgame_allow_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='histogram_bin_count',
            field=models.PositiveIntegerField(default=7, help_text='Use a low nuber to show less detail in the result screen score distribution.', verbose_name='Result screen histogram bins count'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='points_correct',
            field=models.IntegerField(default=1, verbose_name='Amount of points the player gets for a correct answer.'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='points_incorrect',
            field=models.IntegerField(default=-1, help_text='This value needs to be negative to remove points for bad answers.', verbose_name='Amount of points the player gets for an incorrect answer.'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='points_minimum',
            field=models.IntegerField(default=0, help_text='Use to prevent negative points.', verbose_name='Minimum amount of points per question.'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='points_per_question_max',
            field=models.IntegerField(default=4, help_text='Used to calculate what is a perfect score of 100%.', verbose_name='The maximum amount the player can get per question.'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False, verbose_name='Allow player to select more than one answer per question.'),
        ),
    ]
