# Generated by Django 5.2 on 2025-09-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0017_gamesession_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='django_jigsaw_puzzle.game'),
            preserve_default=False,
        ),
    ]
