# Generated by Django 5.2 on 2025-09-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0018_gamesession_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='django_jigsaw_puzzle.quizgame'),
        ),
    ]
