# Generated by Django 5.2 on 2025-09-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('django_jigsaw_puzzle', '0018_quizgame_histogram_bin_count_quizgame_points_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='points_per_question_max',
            field=models.IntegerField(default=4, help_text='Used to calculate what is a perfect score of 100%. E.g. if you quiz has a maximum of 2 correct answers per question and you give 1 point per correct answer, set it to 2.', verbose_name='The maximum amount the player can get per question.'),
        ),
        migrations.CreateModel(
            name='QuizGamePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_jigsaw_puzzle.quizgame')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
