# Generated by Django 5.2 on 2025-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0019_alter_quizgame_points_per_question_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='next_question_timeout',
            field=models.FloatField(default=2, help_text="The amount of time between the user pressing the 'next' button and the following question showing up. If this is too short, the user cannot see what answers were right or wrong, if it's too long, the user game is too slow", verbose_name='Next question timeout (seconds)'),
        ),
    ]
