# Generated by Django 5.2 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jigsaw_puzzle', '0019_alter_quizquestion_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_4',
            field=models.BooleanField(default=False),
        ),
    ]
